spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: mahmudk498@gmail.com
    password: pdjdnumdsdvsoota
    properties:
      mail:
        smtp:
          starttls:
            enable: true
mail:
  subject: Your retirement calculation

